Separate navigation from AudioPlayer
piebrain/G3-FW pull request #28
Opened 2020-12-02 21:57 UTC by piebrain

2020-12-03 02:21 UTC, sastel commented on lib/Compass/INavigation.h
>  class INavigation {
What does the "I" prefix stand for? Interface?

2020-12-03 02:34 UTC, piebrain commented on lib/Compass/INavigation.h
>  class INavigation {
Yes Interface. I know it's really an abstract class... but anyway.

Do you have a better naming convention?

2020-12-03 13:46 UTC, sastel requested changes

2020-12-03 17:19 UTC, piebrain commented on lib/Compass/INavigation.h
>  class INavigation {
It's not uncommon to use Interface as suffix. C# uses the I as a prefix, so that's where I got it from.

2020-12-03 17:22 UTC, piebrain commented on lib/Compass/Navigation2L.cpp
> +    if(data == "")
Personally I like the more condensed code, which is why I also like to put the opening curly braces on the same line as the if statement.

2020-12-03 17:27 UTC, piebrain commented on lib/Compass/PStore.cpp
>              s[i] = file.readStringUntil('\n');
Don't know what the obvious name is, but I'll call it "config" instead

2020-12-03 17:27 UTC, piebrain commented on lib/Compass/Navigation2L.cpp
> +    if(data == "")
It has been changed in the latest revision anyway

2020-12-03 17:45 UTC, piebrain commented on lib/Compass/Navigation2L.cpp
> +Navigation2L::Navigation2L(String navigationData)
This is a onetime operation, so I don't worry about overhead in this case.

Writing to files uses the print functions, so char* could be used instead.

Also, the data is specified by the Navigation class, since it knows which data to save to restore the playing position.

2020-12-03 17:48 UTC, piebrain commented on lib/Compass/PStore.h
> +#define DEBUG_COMPASS_CORE(fmt, ...) DEBUG_ESP_PORT.printf_P( (PGM_P)PSTR(fmt), ##__VA_ARGS__ )
Yes, it's defined in main.h, but this is in the Compass library which knows nothing about main.h. Maybe it should be defined on the library level with a different name.

2020-12-03 17:49 UTC, piebrain commented on lib/Compass/AudioPlayer.cpp
> -void AudioPlayer::nextFolder()
It has nothing to do with playing a file, so it goes elsewhere.

2020-12-03 18:16 UTC, piebrain commented on lib/Compass/AudioPlayer.h
> +    void setVolume(uint8_t vol);
uint8_t has a smaller footprint I believe. Volume is a value from 1-15 so no need for an int

2020-12-03 18:49 UTC, piebrain commented on lib/Compass/Navigation2L.cpp
> +    return 0;
It is meant to represent the navigation level so the LEDs can be updated.

This might be changed later, if we figure a better way of doing this.

2020-12-03 20:46 UTC, piebrain commented on lib/Compass/INavigation.h
>  class INavigation {
Decided to rename to Interface as suffix

2020-12-05 18:39 UTC, sastel approved these changes
I think this rename commit can be dropped if you like. I was originally confused by what the "i" prefix meant but now I understand that it means interface. The "Interface" postfix is quite long.

2020-12-05 19:30 UTC, merged