Js/nav l4 off issue 25
piebrain/G3-FW pull request #48
Opened 2021-02-04 02:36 UTC by steljg

Add 4 Level Nav. Currently breaking 2L nav, to be fixed. Will open another issue to add indexing to 4L nav.

2021-02-04 15:39 UTC, piebrain requested changes
I think you code is fairly easy to understand and it looks good. You do have a lot of redundant code which could be handled better, but that's for another day when we have too much time.

2021-02-04 15:39 UTC, piebrain commented on src/fmpHsm.c
> +            next = requestTransition(msg, NAVIGATE_STATE, NAVIGATE_STATE);
What is the idea behind transition from NAVIGATE_STATE to NAVIGATE_STATE?

2021-02-04 15:39 UTC, piebrain commented on src/main.cpp
> +        LED.showNavLevel(nav->getNavLevel());
Isn't this in a disabled block?

2021-02-06 23:41 UTC, sastel commented on src/fmpHsm.c
> +            next = requestTransition(msg, NAVIGATE_STATE, NAVIGATE_STATE);
Exiting the state disables the pause timeout, and entering it enables the pause timeout. This way any button activity will restart the pause timeout.
I should think about cleaning this function up because it has a high cyclomatic complexity.

2021-02-07 00:30 UTC, sastel commented on src/main.cpp
> +        LED.showNavLevel(nav->getNavLevel());
It is. But we don't want to call showNavLevel here. We should only show the nav level if we are in the NAVIGATE state (i.e. level 2, 3, or 4).

2021-02-07 01:47 UTC, sastel commented on src/main.cpp
> +        LED.showNavLevel(nav->getNavLevel());
- [ ] Get navigation level to show on LED's.

2021-02-10 03:23 UTC, sastel commented
@piebrain this is ready for final review.

- [ ] added 4 level navigation
- [ ] prevented entry into the navigation state (where playback is paused) for devices with 2 level navigation
- [ ] fixed bug in Navigation2L.cpp where next/prev track would loop in the same book
- [ ] show navigation level on LEDs

2021-02-10 11:16 UTC, piebrain approved these changes
Looks pretty good to me.

2021-02-10 12:01 UTC, sastel commented on src/fmpHsm.c
> +        {NAVIGATE_STATE, NAVIGATE_STATE},
No longer need to add transition from Navigate to Navigate since you removed that from the navigate handler.

2021-02-10 12:04 UTC, sastel commented on src/fmpPlayerIF.h
Add show/hideNavLevel

2021-02-10 12:06 UTC, sastel approved these changes

2021-02-10 12:06 UTC, merged