Move files to nav/ and audio/ folders
piebrain/G3-FW pull request #74
Opened 2021-03-24 20:22 UTC by piebrain

2021-03-27 14:58 UTC, sastel commented on lib/Compass/nav/Navigation2L.h
> -#include "nav/FileIndex.h"
I thought that FileIndex.h is still in lib/Compass/nav... why does the include path not say "nav/FileIndex.h" here? Is that because Navigation2L.h is in the same level?

2021-03-27 15:00 UTC, sastel requested changes
@piebrain I'm not against reorganizing the files into sub-directories, but I don't think we should be changing the #include statements to have the path. Otherwise we will have to add commits which change the include path every time we reorganize the files. We should make the build system find the files.

2021-03-27 15:56 UTC, piebrain commented
@sastel I don't know what is best practise when doing this. That's why I ask you to review it!

I not sure I always agree that it should automatically find the header files in sub-folder, but I guess that's more to do with naming conflicts than convenience.

2021-03-27 16:19 UTC, piebrain commented on lib/Compass/nav/Navigation2L.h
> -#include "nav/FileIndex.h"
Can you help me out here? I don't know how to make the compiler include headers in sub-folders.

2021-03-27 19:22 UTC, sastel commented
@piebrain thanks for asking me to review it. :) It is a fairly small project so I don't think we should be concerned at this point with naming conflicts.

2021-03-27 20:43 UTC, piebrain commented
I come from a world (Java and C#) where namespace and folder structure is the standard and flat structure is frowned upon even in small projects. And small projects tend to grow bigger.

My question is how big of a problem is it to change a few includes when files are moved around? We are not moving files very often anyway.

C/C++ probably have a loooong tradition of doing it that way. I think newer languages recommends the hierarchy because they see it as an advantage. Even C++ has more of it these days with the namespace keywords.

2021-03-28 01:03 UTC, sastel commented
These are good points. Let’s have a discussion about it on Zoom soon. You might convince me. 😁

> On Mar 27, 2021, at 4:43 PM, piebrain ***@***.***> wrote:
> 
> I come from a world (Java and C#) where namespace and folder structure is the standard and flat structure is frowned upon even in small projects. And small projects tend to grow bigger.
> 
> My question is how big of a problem is it to change a few includes when files are moved around? We are not moving files very often anyway.
> 
> C/C++ probably have a loooong tradition of doing it that way. I think newer languages recommends the hierarchy because they see it as an advantage. Even C++ has more of it these days with the namespace keywords.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.

2021-03-30 01:25 UTC, sastel approved these changes

2021-03-30 15:32 UTC, merged